### ISSUE TITLE
Documentation: Context (and example?)

### ISSUE THREAD

**Issue by chrysn** [littledivy/webusb#11]
To a newcomer looking at Rust support for WebUSB, the README is lacking information on where in the stack this sits -- could be for use for on the device itself (in embedded Rust), or could run in the browser (eg. through wasm-bindgen).

From the dependencies, I get the impression that it's to be used natively on the host, and peeking at the projects you're involved in it might be the part of WebUSB that runs inside the browser, but that's a guess. If it is right, text like this could be helpful:

> This crate implements the browser part of the WebUSB specification.
> That is, it accesses the host system's USB devices through libusb, and provides the Navigator `.usb` object that is typically used through JavaScript.
>
> An example of how this is used can be found \[in the deno source code\](...).
>
> For different places in the stack where Rust and WebUSB can be used together, see \[usbd-webusb\](https://github.com/redpfire/usbd-webusb) (which would go into the device firmware itself), or \[web-sys's `Usb` struct\](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Usb.html) (which compiled to WebAssembly and run inside the browser). The present crate provides the code inbetween.

(Note that I haven't used or tested usbd-webusb or this particular module of web-sys. These serve not so much as recommendations but more to frame how this crate is used.)

**Comment by littledivy** [comment]
Yes that is right, the crate is intended to be used by the host (natively and WASM). The description looks great, do you mind submitting a PR adding that to the README?
